services:
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  worker:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - network

networks:
  network: {}